server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false

  # 响应页面默认后缀
  mvc:
    view:
      suffix: .html
      prefix: /templates/
    #应该以什么样的路径来访问静态资源,这表示只有静态资源的访问路径为/static/
  #    static-path-pattern: /static/**
  # 数据库连接参数配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://115.29.179.11:3306/graduation_bbs?characterEncoding=UTF-8
#    username: root
#    password: zhangsilence123
    url: jdbc:mysql://127.0.0.1:3306/graduation_bbs?characterEncoding=UTF-8
    username: root
    password: root
    # 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource

#    mongodb数据库连接参数配置
  data:
    mongodb:
      authentication-database: admin
      # 数据库的ip地址
      host: 127.0.0.1
      # MongoDB端口号
      port: 27017
      # 用户账号
      username: admin
      # 用户密码
      password: admin123
      # 指定使用的数据库
      # 不必预先创建，不存在该数据库会自动创建
      database: test


# 扫描实体类设置别名，减少重复书写
mybatis:
  type-aliases-package: cn.graduation.bbs.entity
  mapper-locations: classpath:cn/graduation/bbs/dao/*.xml

#是否激活 swagger true or false
swagger:
  enable: true

